-- Billing policy rides the estate cache — phase 3 of
-- `catalog-platform/docs/info/llm-billing-control-design.md` (§3.4), and the
-- fix for `docs/KNOWN_ISSUES.md` KI-13.
--
-- ## What this column holds
--
-- The `/seen` answer's `billing_denied` array, verbatim, as JSON text — the
-- money-path ids this person may NOT spend on, on THIS instance's site
-- (`library` or `library2`), already resolved by the directory. A consumer
-- applies it as-is and never recomputes it, exactly as it does `estate_status`
-- and `estate_visibility`.
--
-- ## 🔴 NULL MEANS "UNKNOWN". IT DOES NOT MEAN "NOTHING IS DENIED".
--
-- This is the one rule the whole phase rests on, and it is why the column is
-- NULLABLE with no default rather than `DEFAULT '[]'`. `'[]'` is a real answer:
-- *the directory replied and denied nothing*. NULL is the absence of an answer
-- — a row that predates this migration, an auth Worker mid-deploy still running
-- pre-0016 code, a garbled body. A consumer that read the two as the same thing
-- would silently un-switch every policy the owner had set for the length of a
-- deploy, with nothing anywhere going red.
--
-- The pins live at `packages/estate-auth/test/billing-denied-shape.test.ts`.
--
-- ## Why it is a THIRD column and not a widened one
--
-- §4.5's one-answer rule: this fact rides with `estate_status` and
-- `estate_visibility` and ages with them, all three stamped by the single
-- `estate_checked_at`. "May this person spend" and "is this person still a
-- member" are one answer taken at one moment, so they are written in one
-- UPDATE (`writeEstateCache`) and read in one SELECT (`readEstateCache`).
--
-- ## Applying this is safe ahead of the Worker that reads it
--
-- Purely additive: one nullable column on an existing table, no default, no
-- backfill, no constraint. Every existing row reads NULL, which is "unknown",
-- which is today's behaviour. Migrate before deploy, on BOTH instances
-- (`npm run db:migrate:both`) — see `docs/access/deploy.md`.

ALTER TABLE app_user ADD COLUMN estate_billing_denied TEXT;
